// <auto-generated />
using DotNetCoreAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreAPI.Migrations
{
    [DbContext(typeof(DALContext))]
    partial class DALContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCoreAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Category = "Fruit", Description = "12 easy peel clementines", Name = "Jaffa Clementines" },
                        new { Id = 2, Category = "Grocery", Description = "Salted Block Butter 250G", Name = "Block Butter" },
                        new { Id = 3, Category = "Vegtable", Description = "Maris Piper Potatoes 2.5Kg", Name = "Maris Potatoes" },
                        new { Id = 4, Category = "Meat", Description = "Beef Lean Steak Mince 500G 5% Fat", Name = "Lean Mice" },
                        new { Id = 5, Category = "Fruit", Description = "12 easy peel clementines", Name = "Jaffa Clementine" },
                        new { Id = 6, Category = "Fruit", Description = "Fresh Strawberries 400G", Name = "Strawberries" },
                        new { Id = 7, Category = "Fruit", Description = "Red Seedless Grapes 500G", Name = "Grapes" },
                        new { Id = 8, Category = "Meat", Description = "Chicken Breast Portions 650G", Name = "Chicken Breast" },
                        new { Id = 9, Category = "Vegtable", Description = "Brown Onions Minimum 3 Pack 385G", Name = "Onions" },
                        new { Id = 10, Category = "Fruit", Description = "Small Ripe Bananas 6 Pack", Name = "Bananas" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
